//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TF.DBO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThreadMaster
    {
        public ThreadMaster()
        {
            this.Followers = new HashSet<Follower>();
            this.Owners = new HashSet<Owner>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int StatusID { get; set; }
        public Nullable<int> TagID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ICollection<Follower> Followers { get; set; }
        public virtual ICollection<Owner> Owners { get; set; }
        public virtual Status Status { get; set; }
    }
}
